-- Add language columns to posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS title_uz VARCHAR(255);
ALTER TABLE posts ADD COLUMN IF NOT EXISTS title_ru VARCHAR(255);
ALTER TABLE posts ADD COLUMN IF NOT EXISTS title_en VARCHAR(255);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS description_uz TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS description_ru TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS description_en TEXT;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS content_uz TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS content_ru TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS content_en TEXT;

-- Add language columns to ads table
ALTER TABLE ads ADD COLUMN IF NOT EXISTS title_uz VARCHAR(255);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS title_ru VARCHAR(255);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS title_en VARCHAR(255);

ALTER TABLE ads ADD COLUMN IF NOT EXISTS description_uz TEXT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS description_ru TEXT;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS description_en TEXT;

ALTER TABLE ads ADD COLUMN IF NOT EXISTS cta_text_uz VARCHAR(255);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS cta_text_ru VARCHAR(255);
ALTER TABLE ads ADD COLUMN IF NOT EXISTS cta_text_en VARCHAR(255);
